Repository zonkyio/ember-web-app, pull requests merged in 2020-09, with the labels that each got.

#583 Make config path dynamic according to package.json
  blueprints/ember-web-app/files/__config__/manifest.js
  blueprints/ember-web-app/index.js
  lib/base-manifest.js
Labels: bug

#593 Add Ember 3.20 LTS into testing matrix
  .github/workflows/ci.yml
  config/ember-try.js
Labels: internal

#594 Drop Ember 3.12 LTS support
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
  tests/dummy/app/templates/docs/getting-started/upgrade-guide.md
Labels: breaking
